### ISSUE TITLE
Upload data to OpenNeuro

### ISSUE THREAD

**Issue by jcohenadad** [shimming-toolbox/b0-fieldmap-realistic-simulation#9]
Continuation of https://github.com/shimming-toolbox/b0-fieldmap-realistic-simulation/issues/4:

We got the OK from Marseille (Virginie Callot) to upload the T1w data, except these subjects:

- ED
- JD
- JW

Tagging @nathanmolinier @mathieuboudreau

**Comment by NathanMolinier** [comment]
What about T2w ?

**Comment by jcohenadad** [comment]
> What about T2w ?

I need to ask Virginie-- i'll let you know

**Comment by jcohenadad** [comment]
OK for T2w as well

**Comment by mathieuboudreau** [comment]
> * ED
> * JD
> * JW

Is it only the T1w data we must omit, or also all the derivatives?

**Comment by jcohenadad** [comment]
> Is it only the T1w data we must omit, or also all the derivatives?

only the images (T1w and T2w)

**Comment by mathieuboudreau** [comment]
As mentioned in this comment, 

https://github.com/shimming-toolbox/b0-fieldmap-realistic-simulation/issues/4#issuecomment-2451160640

I've gotten to a version of the dataset that is bidsified and uploaded to data.neuro.polymtl.ca for PR review, so I think uploading to OpenNeuro is imminent. The small things that I think could be done to clean up the data are:

1) A few json sidecars of the labels pre: smoothings are empty, and could have some info about who and how they were made if we can collect them. I think only maybe 2 are missing for each subject, centerline and some other one.

2) The derivatives directory structure is messy, in particular I don't like how the labels were set in the derivatives folder and adopted an alternative approach for the chi maps and simulated b0 maps.

For labels, the structure was:

whole-spine/derivatives/labels/subject/anat/*.nii.gz

For the chi and b0 maps, I went with

whole-spine/derivatives/subject/anat/*chi.nii.gz
whole-spine/derivatives/subject/fmap/*b0.nii.gz

The reason why I dislike the label way is that there would have been multiple subject direcctories for each "type" of derivatives, i.e. whole-spine/derivatives/labels/subject, whole-spine/derivatives/anat/subject (for chi), whole-spine/derivatives/fmap/subject. Whereas, my current way, derivatives has the list of all subjects immediately and then in there you can find whatever derivatives you care about.

I'm proposing to move the labels to 

whole-spine/derivatives/subject/labels/*.nii.gz

or

whole-spine/derivatives/subject/anat/*.nii.gz

but prefer the first one, since there are so many of them and only one chi.

Lastly, if I make this change, then the pipelines will need to be updated for this new bids directory derivatives folder structure, and potentially they should all be re-run so the json sidecars have the new structure in their history of how the maps were produced.

After these relatively minor fixes I think we can upload to OpenNeuro if it looks good to everyone else; I think we might not have time to wait for the data.neuro.polymtl.ca PR to be reviewed and merged before uploading to OpenNeuro due to how close the ISMRM deadline is; can revisions be uploaded to OpenNeuro in case additional changes are requested in the PR (eg file naming conventions)?

**Comment by jcohenadad** [comment]
@mathieuboudreau, let's keep it to our internal data server for now-- I need to verify a few additional things about the ethics aspects-- I'll come back to you ASAP

**Comment by mathieuboudreau** [comment]
Ok no worries - I'll wait for a green light on your end !

**Comment by jcohenadad** [comment]
OK-- I just wanted to have Pierre Rainville's acceptance, because the unfPain data are under his ethics-- what we need to do before uploading is get the consent of each participant under that ethics-- i'll take care of it

**Comment by jcohenadad** [comment]
Contacted:

- [ ] sub-unfPain001
- [ ] sub-unfPain002
- [ ] sub-unfPain003
- [ ] sub-unfPain004
- [ ] sub-unfPain005
- [ ] sub-unfPain006

Accepted
- [ ] sub-unfPain001
- [ ] sub-unfPain002
- [ ] sub-unfPain003
- [ ] sub-unfPain004
- [ ] sub-unfPain005
- [ ] sub-unfPain006

**Comment by mathieuboudreau** [comment]
Done, https://openneuro.org/datasets/ds005616

**Comment by NathanMolinier** [comment]
I realize that `JD` is actually present in the dataset

**Comment by mathieuboudreau** [comment]
> I realize that `JD` is actually present in the dataset

I don't see the T1w or T2w data of that subject anywhere,

<img width="348" alt="Screenshot 2024-11-08 at 11 46 38 AM" src="https://github.com/user-attachments/assets/2945e9d5-eb77-409d-9ce2-780ab2d832bc">

Could you point me to it?

**Comment by NathanMolinier** [comment]
Sorry I got confused with `derivatives/labels` subfolder
